// Package config loads and validates Manager's config.yml (architecture-manager.md 9節).
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Default values applied when the corresponding field is left unset.
const (
	DefaultRecordsDir              = "records"
	DefaultEvacuateCompleteSeconds = 30
	DefaultHardcoreReadySeconds    = 120
	DefaultProcessStopSeconds      = 30
	DefaultConfigPath              = "./config.yml"
)

// Config is the top-level shape of config.yml.
type Config struct {
	SignalPort     int      `yaml:"signalPort"`
	GateListenAddr string   `yaml:"gateListenAddr"`
	Hardcore       Hardcore `yaml:"hardcore"`
	Archive        Archive  `yaml:"archive"`
	Timeouts       Timeouts `yaml:"timeouts"`
}

type Hardcore struct {
	WorkDir      string   `yaml:"workDir"`
	StartCommand []string `yaml:"startCommand"`
	RecordsDir   string   `yaml:"recordsDir"`
}

type Archive struct {
	Dir string `yaml:"dir"`
}

type Timeouts struct {
	EvacuateCompleteSeconds int `yaml:"evacuateCompleteSeconds"`
	HardcoreReadySeconds    int `yaml:"hardcoreReadySeconds"`
	ProcessStopSeconds      int `yaml:"processStopSeconds"`
}

// Load reads and validates config.yml at path. Relative paths inside the
// config (hardcore.workDir, archive.dir) are resolved against the Manager
// process's current working directory, not against path's directory
// (architecture-manager.md 9節).
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("config: read %s: %w", path, err)
	}

	var c Config
	if err := yaml.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("config: parse %s: %w", path, err)
	}

	c.applyDefaults()

	if err := c.validate(); err != nil {
		return nil, fmt.Errorf("config: %s: %w", path, err)
	}

	return &c, nil
}

func (c *Config) applyDefaults() {
	if c.Hardcore.RecordsDir == "" {
		c.Hardcore.RecordsDir = DefaultRecordsDir
	}
	if c.Timeouts.EvacuateCompleteSeconds == 0 {
		c.Timeouts.EvacuateCompleteSeconds = DefaultEvacuateCompleteSeconds
	}
	if c.Timeouts.HardcoreReadySeconds == 0 {
		c.Timeouts.HardcoreReadySeconds = DefaultHardcoreReadySeconds
	}
	if c.Timeouts.ProcessStopSeconds == 0 {
		c.Timeouts.ProcessStopSeconds = DefaultProcessStopSeconds
	}
}

func (c *Config) validate() error {
	if c.SignalPort <= 0 {
		return fmt.Errorf("signalPort must be set (>0)")
	}
	if c.GateListenAddr == "" {
		return fmt.Errorf("gateListenAddr must be set")
	}
	if c.Hardcore.WorkDir == "" {
		return fmt.Errorf("hardcore.workDir must be set")
	}
	if len(c.Hardcore.StartCommand) == 0 {
		return fmt.Errorf("hardcore.startCommand must be set")
	}
	if c.Archive.Dir == "" {
		return fmt.Errorf("archive.dir must be set")
	}
	return nil
}

// WorldDir is <hardcore.workDir>/world (the save folder deleted/regenerated by /start, spec 11節).
func (h Hardcore) WorldDir() string {
	return filepath.Join(h.WorkDir, "world")
}

// RecordsPath is <hardcore.workDir>/<recordsDir>, must match the MOD's storage.recordsDir (spec 3.3/5.5節).
func (h Hardcore) RecordsPath() string {
	return filepath.Join(h.WorkDir, h.RecordsDir)
}

// ServerPropertiesPath is <hardcore.workDir>/server.properties, whose hardcore=true
// Manager guarantees on every /start (architecture-manager.md 3節).
func (h Hardcore) ServerPropertiesPath() string {
	return filepath.Join(h.WorkDir, "server.properties")
}

// NamedDir is <archive.dir>/<name>, the root of one archived challenge (spec 3.2/11節).
func (a Archive) NamedDir(name string) string {
	return filepath.Join(a.Dir, name)
}
